# Generated by Django 4.2.2 on 2023-06-14 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_fecha_nacimiento_alter_account_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50, unique=True)),
                ('rut_empresa', models.CharField(max_length=13, unique=True)),
                ('contacto', models.CharField(max_length=50)),
                ('email_contacto', models.EmailField(max_length=254, unique=True, verbose_name='Mail de contacto')),
                ('telefono_contacto', models.CharField(default='', max_length=15)),
                ('fecha_inscripcion', models.DateField(verbose_name=datetime.date(2023, 6, 13))),
            ],
        ),
    ]
